---
project_name: randomapi
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: randomapi
    main: ./cmd/randomapi/main.go
    binary: randomapi
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}

dockers_v2:
  - id: randomapi
    ids:
      - randomapi
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.description: "Tiny HTTP microservice that returns one random element from a JSON array."
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "https://github.com/gi8lino/randomapi"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.url: "https://github.com/gi8lino/randomapi"
      org.opencontainers.image.version: "{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    images:
      - ghcr.io/gi8lino/randomapi
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
